 /* Automatically generated by './build/bin/build-entry.js' */
import lButton from '../src/packages/button/index.js';
import lDialog from '../src/packages/dialog/index.js';
import lTabs from '../src/packages/tabs/index.js';
import lTabItem from '../src/packages/tabItem/index.js';
import lSwitch from '../src/packages/switch/index.js';
import lRadio from '../src/packages/radio/index.js';
import lAlert from '../src/packages/alert/index.js';
import lOption from '../src/packages/option/index.js';
import lSelect from '../src/packages/select/index.js';
import lLoading from '../src/packages/loading/index.js';
import lInput from '../src/packages/input/index.js';
import lContextMenu from '../src/packages/contextMenu/index.js';
const components = [
    lButton,
lDialog,
lTabs,
lTabItem,
lSwitch,
lRadio,
lAlert,
lOption,
lSelect,
lLoading,
lInput,
lContextMenu
]
const install = function (Vue) {
    components.map(v => {
        Vue.component(v.name,v)
    })
    Vue.component(lContextMenu.lContextMenuSubMenu.name,lContextMenu.lContextMenuSubMenu)
    Vue.component(lLoading.loading.name,lLoading.loading)
    Vue.component(lContextMenu.lContextMenu.name,lContextMenu.lContextMenu)
    Vue.use(lContextMenu.contextMenu_directive);
    Vue.use(lLoading.loading_directive);
    Vue.config.globalProperties.$contextMenu = lContextMenu.contextMenu_directive

}
const lUi = {
  install
}
export{
  lButton,
lDialog,
lTabs,
lTabItem,
lSwitch,
lRadio,
lAlert,
lOption,
lSelect,
lLoading,
lInput,
lContextMenu
}
export default lUi
